name: sd-musicgen
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.2
  - torchvision
  - torchaudio
  - pip:
      - gradio
      - diffusers
      - transformers
      - accelerate
      - xformers